# Generated by Django 3.0.8 on 2020-07-30 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtype', models.CharField(max_length=200, verbose_name='Blogtype')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200, unique=True)),
                ('news_slug', models.SlugField(max_length=200, unique=True)),
                ('news_updated_on', models.DateTimeField(auto_now=True)),
                ('news_content', models.TextField()),
                ('videos', embed_video.fields.EmbedVideoField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('news_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('news_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Newsupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=1000, verbose_name='News_Description')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('blog_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('blog_slug', models.SlugField(max_length=200, unique=True)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blogtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_bawabilat_portfolio.BlogType')),
            ],
        ),
    ]
