# Generated by Django 3.0.8 on 2020-08-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bawabilat_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='news_updated_on',
        ),
        migrations.AlterField(
            model_name='newsupdate',
            name='Description',
            field=models.CharField(max_length=100, verbose_name='News Title'),
        ),
        migrations.AlterField(
            model_name='newsupdate',
            name='blog_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='news_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='news_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
