# Generated by Django 3.0.8 on 2020-08-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bawabilat_portfolio', '0002_auto_20200802_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdate',
            name='blog_content',
            field=models.TextField(default=' ', verbose_name='News Content'),
            preserve_default=False,
        ),
    ]
